class AlterTablesAddIndex < ActiveRecord::Migration
  def self.up
    add_index :BANK_TRANSACTION_LINES,  [:BANK_TRANSACTION_ID], :name => 'IDX_BANK_TRANSACTION_LINES_BANK_TRANSACTION_ID', :unique => false 
    add_index :CATALOG_ITEM_LINES, [:CATALOG_ITEM_ID], :name => 'IDX_CATALOG_ITEM_LINES_CATALOG_ITEM_ID', :unique => false 
    add_index :CATALOG_ITEM_PACKET_UPDATE_LINES, [:CATALOG_ITEM_PACKET_UPDATE_ID], :name => 'IDX_CATALOG_ITEM_PACKET_UPDATE_LINES_CATALOG_ITEM_PACKET_UPDATE_ID', :unique => false 
    add_index :CATALOG_ORDER_LINES, [:CATALOG_ORDER_ID], :name => 'IDX_CATALOG_ORDER_LINES_CATALOG_ORDER_ID', :unique => false 
    add_index :CUSTOMER_INVOICE_LINES, [:CUSTOMER_INVOICE_ID], :name => 'IDX_CUSTOMER_INVOICE_LINES_CUSTOMER_INVOICE_ID', :unique => false 
    add_index :CUSTOMER_RECEIPT_LINES, [:CUSTOMER_RECEIPT_ID], :name => 'IDX_CUSTOMER_RECEIPT_LINES_CUSTOMER_RECEIPT_ID', :unique => false
    add_index :DIAMOND_INVENTORY_LINES, [:DIAMOND_INVENTORY_ID], :name => 'IDX_DIAMOND_INVENTORY_LINES_DIAMOND_INVENTORY_ID', :unique => false 
    add_index :DIAMOND_PACKET_UPDATE_LINES, [:DIAMOND_PACKET_UPDATE_ID], :name => 'IDX_DIAMOND_PACKET_UPDATE_LINES_DIAMOND_PACKET_UPDATE_ID', :unique => false 
    add_index :DIAMOND_PURCHASE_LINES, [:DIAMOND_PURCHASE_ID], :name => 'IDX_DIAMOND_PURCHASE_LINES_DIAMOND_PURCHASE_ID', :unique => false 
    add_index :DIAMOND_SALE_LINES,  [:DIAMOND_SALE_ID], :name => 'IDX_DIAMOND_SALE_LINES_DIAMOND_SALE_ID', :unique => false 
    add_index :GL_TRANSACTION_LINES, [:GL_TRANSACTION_ID], :name => 'IDX_GL_TRANSACTION_LINES_GL_TRANSACTION_ID', :unique => false 
    add_index :INVENTORY_TRANSACTION_LINES, [:INVENTORY_TRANSACTION_ID], :name => 'IDX_INVENTORY_TRANSACTION_LINES_INVENTORY_TRANSACTION_ID', :unique => false 
    add_index :POS_INVOICE_LINES, [:POS_INVOICE_ID], :name => 'IDX_POS_INVOICE_LINES_POS_INVOICE_ID', :unique => false 
    add_index :PURCHASE_CREDIT_INVOICE_LINES, [:PURCHASE_CREDIT_INVOICE_ID], :name => 'IDX_PURCHASE_CREDIT_INVOICE_LINES_PURCHASE_CREDIT_INVOICE_ID', :unique => false 
    add_index :PURCHASE_INVOICE_LINES, [:PURCHASE_INVOICE_ID], :name => 'IDX_PURCHASE_INVOICE_LINES_PURCHASE_INVOICE_ID', :unique => false 
    add_index :PURCHASE_MEMO_LINES, [:PURCHASE_MEMO_ID], :name => 'IDX_PURCHASE_MEMO_LINES_PURCHASE_MEMO_ID', :unique => false 
    add_index :PURCHASE_MEMO_RETURN_LINES, [:PURCHASE_MEMO_RETURN_ID], :name => 'IDX_PURCHASE_MEMO_RETURN_LINES_PURCHASE_MEMO_RETURN_ID', :unique => false 
    add_index :PURCHASE_ORDER_CANCEL_LINES, [:PURCHASE_ORDER_CANCEL_ID]  ,:name => 'IDX_PURCHASE_ORDER_CANCEL_LINES_PURCHASE_ORDER_CANCEL_ID', :unique => false 
    add_index :PURCHASE_ORDER_LINES, [:PURCHASE_ORDER_ID], :name => 'IDX_PURCHASE_ORDER_LINES_PURCHASE_ORDER_ID', :unique => false 
    add_index :SALES_CREDIT_INVOICE_LINES, [:SALES_CREDIT_INVOICE_ID], :name => 'IDX_SALES_CREDIT_INVOICE_LINES_SALES_CREDIT_INVOICE_ID', :unique => false 
    add_index :SALES_INVOICE_LINES, [:SALES_INVOICE_ID], :name => 'IDX_SALES_INVOICE_LINES_SALES_INVOICE_ID', :unique => false 
    add_index :SALES_MEMO_LINES, [:SALES_MEMO_ID], :name => 'IDX_SALES_MEMO_LINES_SALES_MEMO_ID', :unique => false 
    add_index :SALES_MEMO_RETURN_LINES, [:SALES_MEMO_RETURN_ID], :name => 'IDX_SALES_MEMO_RETURN_LINES_SALES_MEMO_RETURN_ID', :unique => false 
    add_index :SALES_ORDER_CANCEL_LINES, [:SALES_ORDER_CANCEL_ID],:name => 'IDX_SALES_ORDER_CANCEL_LINES_SALES_ORDER_CANCEL_ID', :unique => false 
    add_index :SALES_ORDER_LINES,  [:SALES_ORDER_ID], :name => 'IDX_SALES_ORDER_LINES_SALES_ORDER_ID', :unique => false 
    add_index :VENDOR_INVOICE_LINES, [:VENDOR_INVOICE_ID], :name => 'IDX_VENDOR_INVOICE_LINES_VENDOR_INVOICE_ID', :unique => false 
    add_index :VENDOR_PAYMENT_LINES, [:VENDOR_PAYMENT_ID], :name => 'IDX_VENDOR_PAYMENT_LINES_VENDOR_PAYMENT_ID', :unique => false 
    #####
    add_index :CATALOG_ATTRIBUTE_VALUES,[:CATALOG_ATTRIBUTE_ID], :name => 'IDX_CATALOG_ATTRIBUTE_VALUES_CATALOG_ATTRIBUTE_ID', :unique => false
    add_index :CATALOG_ITEMS, [:STORE_CODE], :name => 'CATALOG_ITEMS_STORE_CODE', :unique => false 
    add_index :CATALOG_ITEM_PACKETS, [:CATALOG_ITEM_ID], :name=> 'CATALOG_ITEM_PACKETS_CATALOG_ITEM_ID', :unique => false 
    add_index :CATALOG_ITEM_PRICES, [:CATALOG_ITEM_ID], :name => 'CATALOG_ITEM_PRICES_CATALOG_ITEM_ID', :unique => false 
    add_index :CATALOG_ORDERS, [:CUSTOMER_ID], :name => 'CATALOG_ORDERS_CUSTOMER_ID', :unique => false 
    add_index :CUSTOMER_INVOICES, [:CUSTOMER_ID], :name => 'CUSTOMER_INVOICE_CUSTOMER_ID', :unique => false 
    add_index :CUSTOMER_JBTRANKINGS, [:CUSTOMER_ID], :name => 'CUSTOMER_JBTRANKINGS_CUSTOMER_ID', :unique => false 
    add_index :CUSTOMER_NOTES, [:CUSTOMER_ID], :name => 'CUSTOMER_NOTES_CUSTOMER_ID', :unique => false 
    add_index :CUSTOMER_RECEIPTS, [:CUSTOMER_ID], :name => 'CUSTOMER_RECEIPTS_CUSTOMER_ID', :unique => false 
    add_index :CUSTOMER_SHIPPINGS,[:CUSTOMER_ID], :name => 'CUSTOMER_SHIPPINGS_CUSTOMER_ID', :unique => false 
    add_index :DIAMOND_PACKETS, [:DIAMOND_LOT_ID], :name => 'DIAMOND_PACKETS_DIAMOND_LOT_ID', :unique => false 
    add_index :DIAMOND_PURCHASES, [:VENDOR_ID], :name => 'DIAMOND_PURCHASES_VENDOR_ID', :unique => false 
    add_index :DIAMOND_SALES, [:customer_id], :name => 'DIAMOND_SALES_customer_id', :unique => false 
    add_index :INVENTORY_DETAILS, [:COMPANY_ID,:CATALOG_ITEM_ID], :name => 'INVENTORY_DETAILS_COMPANY_ID_CATALOG_ITEM_ID', :unique => false 
    add_index :INVENTORY_SUMMARIES, [:COMPANY_ID,:CATALOG_ITEM_ID], :name => 'INVENTORY_SUMMARIES_COMPANY_ID_CATALOG_ITEM_ID', :unique => false 
    add_index :NOTES, [:TRANS_ID], :name => 'NOTES_TRANS_ID', :unique => false 
    add_index :PURCHASE_CREDIT_INVOICES, [:COMPANY_ID,:TRANS_NO], :name => 'PURCHASE_CREDIT_INVOICES_COMPANY_ID_TRANS_NO', :unique => false 
    add_index :PURCHASE_INVOICES, [:COMPANY_ID,:TRANS_NO], :name => 'PURCHASE_INVOICES_COMPANY_ID_TRANS_NO', :unique => false 
    add_index :PURCHASE_MEMOS, [:COMPANY_ID,:TRANS_NO], :name => 'PURCHASE_MEMOS_COMPANY_ID_TRANS_NO', :unique => false 
    add_index :PURCHASE_MEMO_RETURNS, [:COMPANY_ID,:TRANS_NO], :name => 'PURCHASE_MEMO_RETURNS_COMPANY_ID_TRANS_NO', :unique => false 
    add_index :PURCHASE_ORDERS, [:COMPANY_ID,:TRANS_NO], :name => 'PURCHASE_ORDERS_COMPANY_ID_TRANS_NO', :unique => false 
    add_index :PURCHASE_ORDER_CANCELS, [:COMPANY_ID,:TRANS_NO], :name => 'PURCHASE_ORDER_CANCELS_COMPANY_ID_TRANS_NO', :unique => false 
    add_index :REPORT_COLUMNS, [:COMPANY_ID,:REPORT_ID], :name => 'REPORT_COLUMNS_COMPANY_ID_REPORT_ID', :unique => false 
    add_index :REPORT_LAYOUTS, [:COMPANY_ID,:REPORT_ID], :name => 'REPORT_LAYOUTS_COMPANY_ID_REPORT_ID', :unique => false 
    add_index :REPORT_LAYOUT_COLUMNS, [:COMPANY_ID,:REPORT_LAYOUT_ID], :name => 'REPORT_LAYOUT_COLUMNS_COMPANY_ID_REPORT_LAYOUT_ID', :unique => false 
    add_index :SALES_CREDIT_INVOICES, [:COMPANY_ID,:TRANS_NO], :name => 'SALES_CREDIT_INVOICES_COMPANY_ID_TRANS_NO', :unique => false 
    add_index :SALES_INVOICES, [:COMPANY_ID,:TRANS_NO], :name => 'SALES_INVOICES_COMPANY_ID_TRANS_NO', :unique => false 
    add_index :SALES_MEMOS, [:COMPANY_ID,:TRANS_NO], :name => 'SALES_MEMOS_COMPANY_ID_TRANS_NO', :unique => false 
    add_index :SALES_MEMO_RETURNS, [:COMPANY_ID,:TRANS_NO], :name => 'SALES_MEMO_RETURNS_COMPANY_ID_TRANS_NO', :unique => false 
    add_index :SALES_ORDERS, [:COMPANY_ID,:TRANS_NO], :name => 'SALES_ORDERS_COMPANY_ID_TRANS_NO', :unique => false 
    add_index :SALES_ORDER_CANCELS, [:COMPANY_ID,:TRANS_NO], :name => 'SALES_ORDER_CANCELS_COMPANY_ID_TRANS_NO', :unique => false 
    add_index :TYPES, [:TYPE_CD, :SUBTYPE_CD], :name => 'TYPES_TYPE_CD_SUBTYPE_CD', :unique => false 
    add_index :VENDOR_INVOICES, [:COMPANY_ID,:TRANS_BK, :TRANS_NO], :name => 'VENDOR_INVOICES_COMPANY_ID_TRANS_BK_TRANS_NO', :unique => false 
    add_index :VENDOR_PAYMENTS, [:COMPANY_ID, :TRANS_BK, :TRANS_NO], :name => 'VENDOR_PAYMENTS_COMPANY_ID_TRANS_BK_TRANS_NO', :unique => false 
  end

  def self.down
   remove_index :BANK_TRANSACTION_LINES, :name => :IDX_BANK_TRANSACTION_LINES_BANK_TRANSACTION_ID
   remove_index :CATALOG_ITEM_LINES, :name => :IDX_CATALOG_ITEM_LINES_CATALOG_ITEM_ID
   remove_index :CATALOG_ITEM_PACKET_UPDATE_LINES, :name => :IDX_CATALOG_ITEM_PACKET_UPDATE_LINES_CATALOG_ITEM_PACKET_UPDATE_ID
   remove_index :CATALOG_ORDER_LINES, :name => :IDX_CATALOG_ORDER_LINES_CATALOG_ORDER_ID
   remove_index :CUSTOMER_INVOICE_LINES, :name => :IDX_CUSTOMER_INVOICE_LINES_CUSTOMER_INVOICE_ID
   remove_index :CUSTOMER_RECEIPT_LINES, :name => :IDX_CUSTOMER_RECEIPT_LINES_CUSTOMER_RECEIPT_ID
   remove_index :DIAMOND_INVENTORY_LINES, :name => :IDX_DIAMOND_INVENTORY_LINES_DIAMOND_INVENTORY_ID
   remove_index :DIAMOND_PACKET_UPDATE_LINES, :name => :IDX_DIAMOND_PACKET_UPDATE_LINES_DIAMOND_PACKET_UPDATE_ID
   remove_index :DIAMOND_PURCHASE_LINES, :name => :IDX_DIAMOND_PURCHASE_LINES_DIAMOND_PURCHASE_ID
   remove_index :DIAMOND_SALE_LINES, :name => :IDX_DIAMOND_SALE_LINES_DIAMOND_SALE_ID
   remove_index :GL_TRANSACTION_LINES, :name => :IDX_GL_TRANSACTION_LINES_GL_TRANSACTION_ID
   remove_index :INVENTORY_TRANSACTION_LINES, :name => :IDX_INVENTORY_TRANSACTION_LINES_INVENTORY_TRANSACTION_ID
   remove_index :POS_INVOICE_LINES, :name => :IDX_POS_INVOICE_LINES_POS_INVOICE_ID
   remove_index :PURCHASE_CREDIT_INVOICE_LINES, :name => :IDX_PURCHASE_CREDIT_INVOICE_LINES_PURCHASE_CREDIT_INVOICE_ID
   remove_index :PURCHASE_INVOICE_LINES, :name => :IDX_PURCHASE_INVOICE_LINES_PURCHASE_INVOICE_ID
   remove_index :PURCHASE_MEMO_LINES, :name => :IDX_PURCHASE_MEMO_LINES_PURCHASE_MEMO_ID
   remove_index :PURCHASE_MEMO_RETURN_LINES, :name => :IDX_PURCHASE_MEMO_RETURN_LINES_PURCHASE_MEMO_RETURN_ID
   remove_index :PURCHASE_ORDER_CANCEL_LINES, :name => :IDX_PURCHASE_ORDER_CANCEL_LINES_PURCHASE_ORDER_CANCEL_ID
   remove_index :PURCHASE_ORDER_LINES, :name => :IDX_PURCHASE_ORDER_LINES_PURCHASE_ORDER_ID
   remove_index :SALES_CREDIT_INVOICE_LINES, :name => :IDX_SALES_CREDIT_INVOICE_LINES_SALES_CREDIT_INVOICE_ID
   remove_index :SALES_INVOICE_LINES, :name => :IDX_SALES_INVOICE_LINES_SALES_INVOICE_ID
   remove_index :SALES_MEMO_LINES, :name => :IDX_SALES_MEMO_LINES_SALES_MEMO_ID
   remove_index :SALES_MEMO_RETURN_LINES, :name => :IDX_SALES_MEMO_RETURN_LINES_SALES_MEMO_RETURN_ID
   remove_index :SALES_ORDER_CANCEL_LINES, :name => :IDX_SALES_ORDER_CANCEL_LINES_SALES_ORDER_CANCEL_ID
   remove_index :SALES_ORDER_LINES, :name => :IDX_SALES_ORDER_LINES_SALES_ORDER_ID
   remove_index :VENDOR_INVOICE_LINES, :name => :IDX_VENDOR_INVOICE_LINES_VENDOR_INVOICE_ID
   remove_index :VENDOR_PAYMENT_LINES, :name => :IDX_VENDOR_PAYMENT_LINES_VENDOR_PAYMENT_ID
   #######
    remove_index :CATALOG_ATTRIBUTE_VALUES, :name => 'IDX_CATALOG_ATTRIBUTE_VALUES_CATALOG_ATTRIBUTE_ID'
    remove_index :CATALOG_ITEMS, :name => 'CATALOG_ITEMS_STORE_CODE'
    remove_index :CATALOG_ITEM_PACKETS, :name=> 'CATALOG_ITEM_PACKETS_CATALOG_ITEM_ID'
    remove_index :CATALOG_ITEM_PRICES, :name => 'CATALOG_ITEM_PRICES_CATALOG_ITEM_ID'
    remove_index :CATALOG_ORDERS, :name => 'CATALOG_ORDERS_CUSTOMER_ID'
    remove_index :CUSTOMER_INVOICES, :name => 'CUSTOMER_INVOICE_CUSTOMER_ID'
    remove_index :CUSTOMER_JBTRANKINGS, :name => 'CUSTOMER_JBTRANKINGS_CUSTOMER_ID'
    remove_index :CUSTOMER_NOTES, :name => 'CUSTOMER_NOTES_CUSTOMER_ID'
    remove_index :CUSTOMER_RECEIPTS, :name => 'CUSTOMER_RECEIPTS_CUSTOMER_ID'
    remove_index :CUSTOMER_SHIPPINGS,:name => 'CUSTOMER_SHIPPINGS_CUSTOMER_ID'
    remove_index :DIAMOND_PACKETS, :name => 'DIAMOND_PACKETS_DIAMOND_LOT_ID'
    remove_index :DIAMOND_PURCHASES, :name => 'DIAMOND_PURCHASES_VENDOR_ID'
    remove_index :DIAMOND_SALES, :name => 'DIAMOND_SALES_customer_id'
    remove_index :INVENTORY_DETAILS, :name => 'INVENTORY_DETAILS_COMPANY_ID_CATALOG_ITEM_ID'
    remove_index :INVENTORY_SUMMARIES, :name => 'INVENTORY_SUMMARIES_COMPANY_ID_CATALOG_ITEM_ID'
    remove_index :NOTES, :name => 'NOTES_TRANS_ID'
    remove_index :PURCHASE_CREDIT_INVOICES, :name => 'PURCHASE_CREDIT_INVOICES_COMPANY_ID_TRANS_NO'
    remove_index :PURCHASE_INVOICES, :name => 'PURCHASE_INVOICES_COMPANY_ID_TRANS_NO'
    remove_index :PURCHASE_MEMOS, :name => 'PURCHASE_MEMOS_COMPANY_ID_TRANS_NO'
    remove_index :PURCHASE_MEMO_RETURNS, :name => 'PURCHASE_MEMO_RETURNS_COMPANY_ID_TRANS_NO'
    remove_index :PURCHASE_ORDERS, :name => 'PURCHASE_ORDERS_COMPANY_ID_TRANS_NO'
    remove_index :PURCHASE_ORDER_CANCELS, :name => 'PURCHASE_ORDER_CANCELS_COMPANY_ID_TRANS_NO'
    remove_index :REPORT_COLUMNS, :name => 'REPORT_COLUMNS_COMPANY_ID_REPORT_ID'
    remove_index :REPORT_LAYOUTS, :name => 'REPORT_LAYOUTS_COMPANY_ID_REPORT_ID'
    remove_index :REPORT_LAYOUT_COLUMNS, :name => 'REPORT_LAYOUT_COLUMNS_COMPANY_ID_REPORT_LAYOUT_ID'
    remove_index :SALES_CREDIT_INVOICES, :name => 'SALES_CREDIT_INVOICES_COMPANY_ID_TRANS_NO'
    remove_index :SALES_INVOICES, :name => 'SALES_INVOICES_COMPANY_ID_TRANS_NO'
    remove_index :SALES_MEMOS, :name => 'SALES_MEMOS_COMPANY_ID_TRANS_NO'
    remove_index :SALES_MEMO_RETURNS, :name => 'SALES_MEMO_RETURNS_COMPANY_ID_TRANS_NO'
    remove_index :SALES_ORDERS, :name => 'SALES_ORDERS_COMPANY_ID_TRANS_NO'
    remove_index :SALES_ORDER_CANCELS,:name => 'SALES_ORDER_CANCELS_COMPANY_ID_TRANS_NO'
    remove_index :TYPES, :name => 'TYPES_TYPE_CD_SUBTYPE_CD'
    remove_index :VENDOR_INVOICES, :name => 'VENDOR_INVOICES_COMPANY_ID_TRANS_BK_TRANS_NO'
    remove_index :VENDOR_PAYMENTS, :name => 'VENDOR_PAYMENTS_COMPANY_ID_TRANS_BK_TRANS_NO'
 end
end
