source 'http://rubygems.org'

gem 'rails', '3.1.1'
gem 'linecache19'
gem 'ruby-debug-base19x', '~> 0.11.30.pre4'
gem 'ruby-debug19'
gem 'mongrel', '1.2.0.pre2'
gem 'hpricot','0.8.4'
gem 'chronic','0.6.5'
gem 'parseexcel'
gem 'has_finder'
gem 'linguistics'
gem 'activemerchant'
gem 'authorize-net'
gem 'creditcard'
gem 'ruby-hmac'
gem 'active_shipping'
gem 'time_diff'
gem 'prawn'
# Bundle edge Rails instead:
# gem 'rails',     :git => 'git://github.com/rails/rails.git'

gem 'mysql2'


# Gems used only for assets and not required
# in production environments by default.
group :assets do
  gem 'sass-rails',   '~> 3.1.4'
  gem 'coffee-rails', '~> 3.1.1'
  gem 'uglifier', '>= 1.0.3'
end

gem 'jquery-rails'

# To use ActiveModel has_secure_password
# gem 'bcrypt-ruby', '~> 3.0.0'

# Use unicorn as the web server
# gem 'unicorn'

# Deploy with Capistrano
# gem 'capistrano'

# To use debugger
# gem 'ruby-debug19', :require => 'ruby-debug'

group :test do
  # Pretty printed test output
  gem 'turn', :require => false
end
